[phases.setup]
nixPkgs = ["python39", "freecad", "nodejs", "npm"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "python3 backend/main.py"