name: SwiftFab Multi-Service Template
description: Complete SwiftFab application with database, backend, and frontend services

services:
  - name: swiftfab-database
    source: database
    build:
      builder: RAILWAY
    deploy:
      type: DATABASE
      database: postgres

  - name: swiftfab-backend
    source: .
    build:
      builder: NIXPACKS
    deploy:
      startCommand: python3 backend/main.py
      healthcheckPath: /api/health
      healthcheckTimeout: 100
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10
      dependsOn:
        - swiftfab-database
    environment:
      DATABASE_URL: ${{swiftfab-database.DATABASE_URL}}
      PORT: "8000"

  - name: swiftfab-frontend
    source: frontend
    build:
      builder: NIXPACKS
    deploy:
      startCommand: npm run serve
      healthcheckPath: /
      healthcheckTimeout: 30
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 5
      dependsOn:
        - swiftfab-backend
    environment:
      REACT_APP_API_URL: ${{swiftfab-backend.RAILWAY_PUBLIC_DOMAIN}}
      PORT: "3000"
