[template]
name = "SwiftFab Multi-Service Template"
description = "Complete SwiftFab application with database, backend, and frontend services"

[template.services.database]
name = "swiftfab-database"
source = "database"
build.builder = "RAILWAY"
deploy.type = "DATABASE"
deploy.database = "postgres"

[template.services.backend]
name = "swiftfab-backend"
source = "backend"
build.builder = "NIXPACKS"
deploy.startCommand = "python3 main.py"
deploy.healthcheckPath = "/api/health"
deploy.healthcheckTimeout = 100
deploy.restartPolicyType = "ON_FAILURE"
deploy.restartPolicyMaxRetries = 10
deploy.dependsOn = ["swiftfab-database"]
environment.DATABASE_URL = "${{swiftfab-database.DATABASE_URL}}"
environment.PORT = "8000"

[template.services.frontend]
name = "swiftfab-frontend"
source = "frontend"
build.builder = "NIXPACKS"
deploy.startCommand = "npm run serve"
deploy.healthcheckPath = "/"
deploy.healthcheckTimeout = 30
deploy.restartPolicyType = "ON_FAILURE"
deploy.restartPolicyMaxRetries = 5
deploy.dependsOn = ["swiftfab-backend"]
environment.REACT_APP_API_URL = "${{swiftfab-backend.RAILWAY_PUBLIC_DOMAIN}}"
environment.PORT = "3000"
